name: flutter_project
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # The incorrect, nested http line has been removed from here.

  cupertino_icons: ^1.0.8
  firebase_core: ^3.1.1
  fl_chart: ^0.68.0
  percent_indicator: ^4.2.3
  firebase_database: ^11.0.2
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  image_picker: ^1.1.2
  firebase_storage: ^12.1.0
  flutter_native_splash: ^2.4.0
  http: ^1.2.1 # This is the single, correctly placed http package.
  geolocator: ^12.0.0
  flutter_animate: ^4.5.0
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/logo.png

flutter_native_splash:
  color: "#1a1a1a" 

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"