// lib/firebase_options.dart

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOUjUzz8T_IYxiCHl_xmSBo8dt9_UWTD0',
    appId: '1:712147450416:web:b18e09ffc8e1c8ba554bf5',
    messagingSenderId: '712147450416',
    projectId: 'ecogrid-monitor',
    authDomain: 'ecogrid-monitor.firebaseapp.com',
    // THIS LINE WAS ADDED
    databaseURL: 'https://ecogrid-monitor-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecogrid-monitor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe5UHKS9SBl-yd4u3Cdm5R68oYBpINqcw',
    appId: '1:712147450416:android:a640492c39f884f2554bf5',
    messagingSenderId: '712147450416',
    projectId: 'ecogrid-monitor',
    // THIS LINE WAS ADDED
    databaseURL: 'https://ecogrid-monitor-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecogrid-monitor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaXGF1aui0yK2TC6e0lXbU8FbctaI7llc',
    appId: '1:712147450416:ios:b79ac14b81e32a30554bf5',
    messagingSenderId: '712147450416',
    projectId: 'ecogrid-monitor',
    // THIS LINE WAS ADDED
    databaseURL: 'https://ecogrid-monitor-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecogrid-monitor.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaXGF1aui0yK2TC6e0lXbU8FbctaI7llc',
    appId: '1:712147450416:ios:b79ac14b81e32a30554bf5',
    messagingSenderId: '712147450416',
    projectId: 'ecogrid-monitor',
    // THIS LINE WAS ADDED
    databaseURL: 'https://ecogrid-monitor-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecogrid-monitor.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOUjUzz8T_IYxiCHl_xmSBo8dt9_UWTD0',
    appId: '1:712147450416:web:0f9fa5740b9e2cb9554bf5',
    messagingSenderId: '712147450416',
    projectId: 'ecogrid-monitor',
    authDomain: 'ecogrid-monitor.firebaseapp.com',
    // THIS LINE WAS ADDED
    databaseURL: 'https://ecogrid-monitor-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecogrid-monitor.firebasestorage.app',
  );
}